BINDING_HEADER_SHADOWPAD = "ShadowPad";

BINDING_NAME_SHADOWPAD_BUTTON_F1 = "Binding Button F1";
BINDING_NAME_SHADOWPAD_BUTTON_F2 = "Binding Button F2";
BINDING_NAME_SHADOWPAD_BUTTON_F3 = "Binding Button F3";
BINDING_NAME_SHADOWPAD_BUTTON_F4 = "Binding Button F4";
BINDING_NAME_SHADOWPAD_BUTTON_F5 = "Binding Button F5";

BINDING_NAME_SHADOWPAD_BUTTON_1 = "Binding Button 1";
BINDING_NAME_SHADOWPAD_BUTTON_2 = "Binding Button 2";
BINDING_NAME_SHADOWPAD_BUTTON_3 = "Binding Button 3";
BINDING_NAME_SHADOWPAD_BUTTON_4 = "Binding Button 4";
BINDING_NAME_SHADOWPAD_BUTTON_5 = "Binding Button 5";

BINDING_NAME_SHADOWPAD_BUTTON_Q = "Binding Button Q";
--BINDING_NAME_SHADOWPAD_BUTTON_W = "Movement Button W";
BINDING_NAME_SHADOWPAD_BUTTON_E = "Binding Button E";
BINDING_NAME_SHADOWPAD_BUTTON_R = "Binding Button R";
BINDING_NAME_SHADOWPAD_BUTTON_T = "Binding Button T";

--BINDING_NAME_SHADOWPAD_BUTTON_A = "Movement Button A";
--BINDING_NAME_SHADOWPAD_BUTTON_S = "Movement Button S";
--BINDING_NAME_SHADOWPAD_BUTTON_D = "Movement Button D";
BINDING_NAME_SHADOWPAD_BUTTON_F = "Binding Button F";
BINDING_NAME_SHADOWPAD_BUTTON_G = "Binding Button G";
BINDING_NAME_SHADOWPAD_BUTTON_H = "Binding Button H";

BINDING_NAME_SHADOWPAD_BUTTON_Z = "Binding Button Z";
BINDING_NAME_SHADOWPAD_BUTTON_X = "Binding Button X";
BINDING_NAME_SHADOWPAD_BUTTON_C = "Binding Button C";
BINDING_NAME_SHADOWPAD_BUTTON_V = "Binding Button V";
BINDING_NAME_SHADOWPAD_BUTTON_B = "Binding Button B";
BINDING_NAME_SHADOWPAD_BUTTON_N = "Binding Button N";
BINDING_NAME_SHADOWPAD_BUTTON_M = "Binding Button M";

if (GetLocale() == "deDE") then
	SHADOWPAD_SHADOWDANCE = "Schattentanz";
elseif (GetLocale() == "frFR") then
	SHADOWPAD_SHADOWDANCE = "Danse de l'ombre";
elseif (GetLocale() == "esES") then
	SHADOWPAD_SHADOWDANCE = "Danza de las Sombras";
elseif (GetLocale() == "ruRU") then
	SHADOWPAD_SHADOWDANCE = "Танец теней";
else
	SHADOWPAD_SHADOWDANCE = "Shadow Dance";
end
